[package]
name = "datart"
version = "0.1.5"
description = "Tri local de fichiers Excel"
authors = ["Datart"]
edition = "2021"

[lib]
name = "datart_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
